### ISSUE TITLE
Import error with PyQt4.QtGui in Travis 

### ISSUE THREAD

**Issue by tushar-rishav** [tushar-rishav/code2pdf#11]
I've been trying to run tests on Travis. For that I need to first have `PyQt4.Gui` module installed as one of the dependencies. I'am executing [install.sh](https://github.com/tushar-rishav/code2pdf/blob/travis_fix/.misc/install.sh#L4) to install PyQt4. One can see that the module has been installed perfectly at [travis dist-packages](https://travis-ci.org/tushar-rishav/code2pdf#L213). 
Sadly, the module [isn't available for import](https://travis-ci.org/tushar-rishav/code2pdf#L221). 
Am I missing something here?
(Refer branch - `travis_fix`)

**Comment by AbdealiLoKo** [comment]
Hm, I've not really used qt much. But your commands do not seem to work on ubuntu 14.04.

EDIT: Sorry. I was running a virtualenv. It does seem to work.

Seems like you have the same problem :p https://github.com/python-pillow/Pillow/issues/813
Travis runs python in a virtualenv, because of which apt-get packages aren't used. You probably want to use `system_site_packages` like how they do it there

EDIT 2:
Apparently there is a known bug in travis https://github.com/travis-ci/travis-ci/issues/4260
But as you're only running travis for 2.7 it should be fine

**Comment by tushar-rishav** [comment]
Hm maybe it's not installed for Python3? Could you please try again for
Python2 and let me know.

**Comment by AbdealiLoKo** [comment]
Could you check the comment on github ?
I edited it multiple times to avoid spamming you :)

**Comment by tushar-rishav** [comment]
Oh sure. Need to switch to PC for that. :D :+1:

**Comment by tushar-rishav** [comment]
Thanks. The problem related to this issue has been solved. Closing in favor of https://github.com/tushar-rishav/code2pdf/issues/12
