### ISSUE TITLE
Packaging name problem

### ISSUE THREAD

**Issue by lpointal** [tushar-rishav/code2pdf#25]
Hello, just installed via pip under anaconda, and tested via command-line.

The package directory is named Code2pdf (with uppercase C), but __init__.py import code2pdf.main (with lowercase c).

(base) pointal@motus:~$ code2pdf -h
Traceback (most recent call last):
  File "/people/pointal/apps/anaconda3/bin/code2pdf", line 7, in <module>
    from Code2pdf import main
  File "/people/pointal/apps/anaconda3/lib/python3.7/site-packages/Code2pdf/__init__.py", line 1, in <module>
    from code2pdf import main
ModuleNotFoundError: No module named 'code2pdf'

**Comment by tushar-rishav** [comment]
@lpointal Sorry about that and thanks for reporting. The error is due to Python3 incompatibility. 
Please refer :
https://stackoverflow.com/a/48116074/3673031
https://www.python.org/dev/peps/pep-0328/#guido-s-decision

I don't have bandwidth this week. I can add a patch over weekend to make this module compatible with Python 3. Meanwhile, if possible, I suggest you to use Python 2 to unblock yourself.
Here's how:
```bash
pipenv shell --two
pip install code2pdf
code2pdf -h
```

Btw, I'll be very happy to receive a PR fixing this issue. :)

**Comment by Manav1918** [comment]
I have the same issue..
How to solve

**Comment by batuhaneralp** [comment]
1) Go to C:\Users\USER_NAME\AppData\Local\Programs\Python\Python36\Lib\site-packages\Code2pdf
2) Open __init__.py
3) Change "from code2pdf import main" to "from .code2pdf import main"
4) Install PyQt4 (for windows, you can find whl files in https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4 )
5) Run your code and that should be it

**Comment by Manav1918** [comment]
What's the error? Send ScreenShot

Thank you!
Pawan,
CID An Education Hub

**Comment by tushar-rishav** [comment]
This issue has been fixed in https://github.com/tushar-rishav/code2pdf/pull/29
My sincere thanks to [@Thommy257](https://github.com/Thommy257) for the contribution.

**Comment by Manav1918** [comment]
Thank you!
Pawan,
CID An Education Hub
